### ISSUE TITLE
Resetting Forms

### ISSUE THREAD

**Issue by Annoynamous72z** [edabonacci/2DHockey#16]
Once you use the quit button from the pause menu in the main game, forms team selection and the main game are not reset

**Comment by ewdyang** [comment]
Fixed for main game with commit e90e01d4eafb044c5584e11cc80972899ef07066

**Comment by ewdyang** [comment]
Fixed for team selection with 80cc775adff1498f013a8739e45f428fc800c76d
That should be it for now.
