### ISSUE TITLE
Comp or 2 player?

### ISSUE THREAD

**Issue by ewdyang** [edabonacci/2DHockey#18]
A decision needs to be made on whether the second player will be controlled by the computer, or by a second player.

**Comment by Annoynamous72z** [comment]
Which one is easier?

**Comment by ewdyang** [comment]
At this point in time, making it a second controllable player would be easier than trying to implement an AI to control it.

**Comment by Annoynamous72z** [comment]
We should do a second controllable player so we can have something to hand
in by Wednesday.

**Comment by ewdyang** [comment]
Pinging PlumSauc3 and Bigbadpig13

**Comment by ewdyang** [comment]
2 Player has been successfully implemented.
